/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 86cd06d22f6c81a0b776b2d6de030061)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "YahooFinanceMCP";
	}
	interface Env {
		YahooFinanceMCP: DurableObjectNamespace<import("./src/server").YahooFinanceMCP>;
	}
}
interface Env extends Cloudflare.Env {}
